### ISSUE TITLE
Thumbnails don't respect width and height if Crop not checked

### ISSUE THREAD

**Issue by georgema1982** [stefanfoulis/cmsplugin-filer#165]
For each image, I can enter width and height and check Crop and Upscale. So far I notice that if I leave Crop unchecked, the generated thumbnail doesn't respect the width and height I enter. It seems to me that easy thumbnail generates a thumbnail that shrinks proprotionally to fit either width or height. This is not what I expected.

For example, I have a image of 1623 * 1080. I specify the thumbnail should be 970 * 300 and leave Crop unchecked. I expect the thumbnail to be processed to be the dimension I specified. But the actually result is a image of 451 * 300 and the img tag is told to be 970 * 300.

Maybe my usage is wrong. But I hope it can respect the width and height if Crop is not checked.

**Comment by yakky** [comment]
@georgema1982 that's the intended behavior qas documented in http://easy-thumbnails.readthedocs.org/en/latest/ref/processors/
crop option is obviously required to force the image to fixed sizes as the original w/h ratio must be preserved in proportional resizing
