### ISSUE TITLE
Folder migration 0003 breaks on Django CMS 3 - develops

### ISSUE THREAD

**Issue by peterfarrell** [stefanfoulis/cmsplugin-filer#171]
https://github.com/stefanfoulis/cmsplugin-filer/blob/develop/cmsplugin_filer_folder/migrations/0003_move_view_option_to_style.py

The renaming of the table breaks with the current develops version of django-cms to the addition of Treebeard and the removal of rght and lft fields in the cmsplugin model.

rght and lft were removed in:

0072_auto__del_field_cmsplugin_rght__del_field_cmsplugin_level__del_field_c.py

So a depends on migration needs to be added for 0071

**Comment by georgema1982** [comment]
Does that imply that current stable release is only compatible with django cms 3.0?

**Comment by yakky** [comment]
Fixed by #172 
@georgema1982 expect a release including this fix really soon
